### PR TITLE
[Feature] Add Huggingface TGI interface support

### PR DESCRIPTION
**Pull request by dr3s**

### CODE REVIEW

**Comment by xieus** [comment]
Hi @dr3, Thanks for your contribution to LLM perf repo. There is some merge conflict of this PR. Can you please address it? Thanks.

**Comment by dr3s** [comment]
@xieus rebased

**Review by cadedaniel — APPROVED** [review]

**Comment by dr3s** [comment]
@cadedaniel can this be merged, so I don't have to rebase again?

**Comment by cadedaniel** [comment]
cc @xieus who has permissions to merge

**Pull request merged**
